from scripts import spotifyapi, runnode, utils

# ------------------------------- #
# main

# playlist = spotifyapi.create_playlist("sample2", "sample for generating playlists")
# # playlist = spotifyapi.Playlist("https://open.spotify.com/playlist/7eMqBWauas5mg8wKkHgldg?si=52070a388cba451c")

# endpoint = "https://api.spotify.com/v1/recommendations?"
# seed_song = spotifyapi.Song('https://open.spotify.com/track/45HHTHXv7gQ5q2r89ui2Fy?si=28c6f22236904025')

# print(seed_song)
"""
TODO: 
short term
1. function for generating playlists -- or make a class lmao
2. IMPROATJPAOJ PWAJ 
- MULTIPLE seed songs!!!!!
3. 

long term
1. allow different users to get playlists generated for them
"""

# seed_song = spotifyapi.Song(input("Input a seed song link: "))
seed_songs = [spotifyapi.Song("https://open.spotify.com/track/2soCr3tI1sJ6lFrxBPQVzQ?si=326ce0653d664434"),
    spotifyapi.Song("https://open.spotify.com/track/6hytpsQlp7dDrqyHN6WtNN?si=602cdbe3740e48d8")]
# for i in range(int(input("How many more seed songs?: "))):
# songs.append(spotifyapi.Song(input(f"Input a {i+1} link: ")))

playlist = spotifyapi.Playlist(
    "https://open.spotify.com/playlist/1UbmijbVeGxhWZHsJP6A5E?si=13aa3d3a66f14d22"
)

# print(playlist.get_songs())
# paths = runnode.download_songs(
#     songs=playlist.get_songs(),
#     path="assets/" + utils.remove_illegal_file_chars(playlist.name),
# )
# save to file
# runnode.save_paths_to_file(paths, ".blob/audio_concat.txt")


# playlist = spotifyapi.create_playlist("insert name", "generated by petthepotat SpotifyGenerator :)")
# playlist = spotifyapi.Playlist(
#     "https://open.spotify.com/playlist/1UAQ7WYIxbptNETMqbemLQ?si=57c67fb3317a49aa"
# )
# runnode.download_songs(playlist.get_songs(), "assets/" + playlist.name)

# exit()




# TODO -- get avg values for seed song data

# playlist.add_songs(songs=[seed_song])
rec = spotifyapi.Recommendation(
    limit=15,
    market="US",
    seed_tracks=spotifyapi.Recommendation.generate_seed_song_array(seed_songs),
    danceability=seed_songs[0].danceability,
    energy=seed_songs[0].energy,
    instrumentalness=seed_songs[0].instrumentalness,
    liveness=seed_songs[0].liveness,
    loudness=seed_songs[0].loudness,
    speechiness=seed_songs[0].speechiness,
    tempo=seed_songs[0].tempo,
    valence=seed_songs[0].valence,
)
# runnode.download_songs(rec.get_recommendations(), "assets/" + playlist.name)
res = playlist.add_songs(rec.get_recommendations())
print(res)
