from scripts import spotifyapi, runnode, utils

# ------------------------------- #
# main

# playlist = spotifyapi.create_playlist("sample2", "sample for generating playlists")
# # playlist = spotifyapi.Playlist("https://open.spotify.com/playlist/7eMqBWauas5mg8wKkHgldg?si=52070a388cba451c")

# endpoint = "https://api.spotify.com/v1/recommendations?"
# seed_song = spotifyapi.Song('https://open.spotify.com/track/45HHTHXv7gQ5q2r89ui2Fy?si=28c6f22236904025')

# print(seed_song)
"""
TODO: 
short term
1. function for generating playlists -- or make a class lmao
2. IMPROATJPAOJ PWAJ 
- MULTIPLE seed songs!!!!!
3. 

long term
1. allow different users to get playlists generated for them
"""


seed_song = spotifyapi.Song(
    "https://open.spotify.com/track/2rFkefEg2uZMVcmCSbgiJf?si=45274b8ad1444383"
)
# seed_song = spotifyapi.Song(input("Input a seed song link: "))
songs = [seed_song]
# for i in range(int(input("How many more seed songs?: "))):
# songs.append(spotifyapi.Song(input(f"Input a {i+1} link: ")))

playlist = spotifyapi.Playlist(
    "https://open.spotify.com/playlist/1byYwWilkxBgQOnghnG5fy?si=b26d9a19cbde4a44"
)

# print(playlist.get_songs())
paths = runnode.download_songs(
    songs=playlist.get_songs(),
    path="assets/" + utils.remove_illegal_file_chars(playlist.name),
)
# save to file
runnode.save_paths_to_file(paths, ".blob/audio_concat.txt")


# playlist = spotifyapi.create_playlist("insert name", "generated by petthepotat SpotifyGenerator :)")
# playlist = spotifyapi.Playlist(
#     "https://open.spotify.com/playlist/1UAQ7WYIxbptNETMqbemLQ?si=57c67fb3317a49aa"
# )
# runnode.download_songs(playlist.get_songs(), "assets/" + playlist.name)

exit()


# playlist.add_songs(songs=[seed_song])
rec = spotifyapi.Recommendation(
    limit=5,
    market="US",
    seed_tracks=spotifyapi.Recommendation.generate_seed_song_array(songs),
    danceability=seed_song.danceability,
    energy=seed_song.energy,
    instrumentalness=seed_song.instrumentalness,
    liveness=seed_song.liveness,
    loudness=seed_song.loudness,
    speechiness=seed_song.speechiness,
    tempo=seed_song.tempo,
    valence=seed_song.valence,
)
runnode.download_songs(rec.get_recommendations(), "assets/" + playlist.name)
# playlist.add_songs(rec.get_recommendations())
